# Generated by Django 4.1.3 on 2022-11-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('imgus', models.ImageField(upload_to='', verbose_name='Фото о нас')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photobook', models.ImageField(upload_to='', verbose_name='Фото для книги')),
                ('title', models.TextField(blank=True, verbose_name='Название книги')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=150, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=150, verbose_name='Ответ')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото для помощи')),
            ],
            options={
                'verbose_name_plural': 'Помощь',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название товара')),
                ('author', models.TextField(max_length=25, verbose_name='Автор')),
                ('janr', models.CharField(max_length=20, verbose_name='Жанр')),
                ('sheet', models.CharField(blank=True, max_length=25, verbose_name='Кол-во страниц')),
                ('lang', models.TextField(blank=True, verbose_name='Язык')),
                ('pub_date', models.DateTimeField(verbose_name='Год выпуска')),
                ('pricebook', models.IntegerField(blank=True, verbose_name='Цена')),
                ('old_price', models.IntegerField(verbose_name='Старая Цена')),
                ('pricediscount', models.IntegerField(verbose_name='Процент скидки')),
                ('hitofsales', models.BooleanField(verbose_name='Хит продаж')),
                ('newtov', models.BooleanField(verbose_name='Новинки')),
                ('poiskizbrannye', models.BooleanField(verbose_name='Избранные')),
                ('bookcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='knigi.category')),
            ],
        ),
    ]
