# Generated by Django 4.1.3 on 2022-11-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knigi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Все книги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.TextField(max_length=10, verbose_name='Автор'),
        ),
    ]
