# Generated by Django 4.1.3 on 2022-11-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knigi', '0002_alter_books_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='title',
        ),
    ]
